<?php

namespace grozzzny\widgets\map\assets;

use yii\web\AssetBundle;

class MapApiAsset extends AssetBundle
{
    public $sourcePath = '@grozzzny/widgets/map/assets';

    public $key = null;

    public $js = [];

    public function init()
    {
        $apikey = empty($this->key) ? '' : 'apikey='.$this->key.'&';

        array_unshift($this->js, '//api-maps.yandex.ru/2.1/?'.$apikey.'lang=' . preg_replace('/-.*/i', '', \Yii::$app->language));

        parent::init(); // TODO: Change the autogenerated stub
    }
}
