<?php

namespace grozzzny\widgets\map\assets;

use yii\web\AssetBundle;

class MapAsset extends AssetBundle
{
    public $sourcePath = '@grozzzny/widgets/map/assets';

    public $key = null;

    public $js = [
        'map.js',
        'ymaps.arrow.js',
    ];

    public $depends = [
        'yii\web\JqueryAsset',
    ];

    public function init()
    {
        $apikey = empty($this->key) ? '' : 'apikey='.$this->key.'&';

        array_unshift($this->js, '//api-maps.yandex.ru/2.1/?'.$apikey.'lang=' . preg_replace('/-.*/i', '', \Yii::$app->language));

        parent::init(); // TODO: Change the autogenerated stub
    }
}
