<?php

namespace grozzzny\widgets\map\assets;

use yii\web\AssetBundle;

class MapAsset extends AssetBundle
{
    public $sourcePath = '@grozzzny/widgets/map/assets';

    public $js = [
        'map.js',
    ];

    public $depends = [
        'yii\web\JqueryAsset',
    ];

    public function init()
    {
        $this->js[] = '//api-maps.yandex.ru/2.1/?lang=' . Yii::$app->lang;
        parent::init(); // TODO: Change the autogenerated stub
    }
}
